### ISSUE TITLE
no utils script

### ISSUE THREAD

**Issue by LeoMax-Xiong** [jefflai108/ASSERT#1]
Hi,
I don't find any script about the feature or directory utils, can you please release such scripts about the feature

**Comment by jefflai108** [comment]
hi @Honei 
Sorry for the late reply. I was on vacation. Have you set up Kaldi? 
If you do, the utils/ or steps/ or sid/ directories are the ones in the Kaldi egs. For example https://github.com/kaldi-asr/kaldi/tree/master/egs/sre16/v1

You can just soft link those directories to the current working dir. 

Let me know if you have further trouble :)
