### ISSUE TITLE
logspec feature extraction from run_features.sh

### ISSUE THREAD

**Issue by braveheartwithlove** [jefflai108/ASSERT#12]
@jefflai108 Would you mind explain a little bit what does the difference of extracting feature of logspec in the last two 2 stages https://github.com/jefflai108/ASSERT/blob/master/features/run_feature.sh#L329-L362, comparing with the beginning part (which you also have the logspec for eval, train and dev separately)?

Thanks

**Comment by AnkitaBeniwal** [comment]
Hi @braveheartwithlove could you find a solution because I noticed you closed the issue.
