### ISSUE TITLE
can you give me some guidance on how to use Bosaris toolkit 

### ISSUE THREAD

**Issue by LoveSiameseCat** [jefflai108/ASSERT#16]
Hi,
   I'm interested in this challenge, and designed some single anti-spoofing model for LA dataset. When I read the related papers in ASVspoof2019 Challenge, I found many primary systems are obtained by fusing some single models. I want to use Bosaris toolkit to fuse my model, but I have no idea how to use it, can you offer a demo code?

**Comment by MrJack99** [comment]
Do you know now？ I‘m reading the related papers in ASVspoof2019 Challenge now. I want to use Bosaris toolkit to fuse my model, but I have no idea how to use it....
