### ISSUE TITLE
./run_feature.sh: line 18: data/la_eval/spk2utt: No such file or directory

### ISSUE THREAD

**Issue by DeeDive** [jefflai108/ASSERT#2]
I tried to run the feature extraction script:

./run_feature.sh: line 18: data/la_eval/spk2utt: No such file or directory

Could you please help me?

Thank you very much

**Comment by jefflai108** [comment]
Hi @Infinitestudy 

Please check out this issue: 
https://github.com/jefflai108/Attentive-Filtering-Network/issues/3

An example of spk2utt for this dataset would be:
LA_E_1000147 LA_E_1000147-LA_E_1000147
LA_E_1000273 LA_E_1000273-LA_E_1000273
LA_E_1000791 LA_E_1000791-LA_E_1000791
LA_E_1000841 LA_E_1000841-LA_E_1000841

Let me know if you have further trouble :)

**Comment by DeeDive** [comment]
Hi @jefflai108 ,

I've successfully created scp file with your help.

To extract logspec used in the paper, I changed the $stage in run_feature.sh to 0 .
File local/make_spectrogram.sh is missing, so I copied the one from your AFN repo.

But it seems that feature extraction processes in make_spectrogram.sh does not work properly since the resource usage is almost zero. Is there anything wrong with me? 

> fix_data_dir.sh: kept all 134730 utterances.
fix_data_dir.sh: old files are kept in data/pa_eval/.backup
utils/copy_data_dir.sh: copied data from data/pa_eval to data/pa_eval_spec
utils/validate_data_dir.sh: Successfully validated data-directory data/pa_eval_spec
local/make_spectrogram.sh --fbank-config conf/spec.conf --nj 40 --cmd run.pl data/pa_eval_spec exp/make_spec /home/bill/ASSERT/features/logspec
utils/validate_data_dir.sh: Successfully validated data-directory data/pa_eval_spec
local/make_spectrogram.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.
run.pl: 40 / 40 failed, log is in exp/make_spec/make_fbank_pa_eval_spec.*.log


Millions of thanks in advance
