### ISSUE TITLE
problem in main.py

### ISSUE THREAD

**Issue by wuqiangch** [jefflai108/ASSERT#5]
How to generate these files in main.py
    data_files = { # training 
        'train_scp': 'data_reader/feats/la_train_spec_tensor4.scp',
        'train_utt2index': 'data_reader/utt2systemID/la_train_utt2index_8',
        'dev_scp': 'data_reader/feats/la_dev_spec_tensor4.scp',
        'dev_utt2index': 'data_reader/utt2systemID/la_dev_utt2index_8',
        'dev_utt2systemID': 'data_reader/utt2systemID/la_dev_utt2systemID',
        'scoring_dir': 'scoring/la_cm_scores/',
    }

**Comment by wuqiangch** [comment]
I have successfully get the feature by run_feature.sh

**Comment by braveheartwithlove** [comment]
@wuqiangch @jefflai108 Would you mind describing what those files mean and what they look like?
'dev_scp': 'data_reader/feats/la_dev_spec_tensor4.scp',
'dev_utt2index': 'data_reader/utt2systemID/la_dev_utt2index_8',
'dev_utt2systemID': 'data_reader/utt2systemID/la_dev_utt2systemID',

Thanks

**Comment by Lebenslang** [comment]
> I have successfully get the feature by run_feature.sh

Could you describe your environment configuration to run run_features.sh? I can't run it successfully.
