### ISSUE TITLE
the pretrained/pa/senet34 is binary_class?

### ISSUE THREAD

**Issue by wuqiangch** [jefflai108/ASSERT#6]
the pretrained/pa/senet34 is binary_class, It has two class:spoof and bonafide

**Comment by wuqiangch** [comment]
@jefflai108 I used this model to dev database, and get EER_CM: 0.592592592593. 
 I alse have a  question. how to train this model ,only set NUM_SPOOF_CLASS=2?

**Comment by wuqiangch** [comment]
@jefflai108  By setting  NUM_SPOOF_CLASS=10,  I  can get eer =0.797 on pa-dev database.

**Comment by wangtao2668129173** [comment]
> @jefflai108 I used this model to dev database, and get EER_CM: 0.592592592593.
> I alse have a question. how to train this model ,only set NUM_SPOOF_CLASS=2?

hi,I didn't measure it by 0.59%,l test it 58%，can you help me?thank you.
