### ISSUE TITLE
How using python to get the logspec?

### ISSUE THREAD

**Issue by wuqiangch** [jefflai108/ASSERT#7]
I use the code to extract logspec, but the feature is different from kaldi.
   s = librosa.core.stft(x, n_fft=n_fft, win_length=win_length, hop_length=hop_length)
   a = np.abs(s)**2
   mag_T = librosa.power_to_db(a)

**Comment by jefflai108** [comment]
hi @wuqiangch 

yes, Librosa is an alternative choice. But make sure the STFT parameters are the same.
