### ISSUE TITLE
the problem of training model by SENet34

### ISSUE THREAD

**Issue by wuqiangch** [jefflai108/ASSERT#8]
@jefflai108
On dev database,
I  set NUM_SPOOF_CLASS=2,only can get eer=0.869.
I  set NUM_SPOOF_CLASS=10,only can get err=0.797.
Can you give some help ? Thanks!

**Comment by jefflai108** [comment]
From what I remember, it's pretty easy to get 0% EER on the DEV set. These are my suggestion: 
1. Can you first load the pre-trained models and see if you can get the reported EERs? If not, your setup may be wrong in the first place. 
2. I am guessing your feature may be wrong. Check out the feature preparation part in the paper. 
3. Train a few more times (for each model) and analyze the results.

**Comment by wuqiangch** [comment]
@jefflai108 I used the pre-trainded model on PA dev database, and get EER_CM: 0.592592592593.
But in your paper the eer is 0.575.

**Comment by jefflai108** [comment]
you mentioned you use Librosa for feature extraction. That may be another source of variation.

**Comment by wuqiangch** [comment]
@jefflai108 No, I use your code to extract feature.It means kaldi.

**Comment by wangtao2668129173** [comment]
> @jefflai108
> On dev database,
> I set NUM_SPOOF_CLASS=2,only can get eer=0.869.
> I set NUM_SPOOF_CLASS=10,only can get err=0.797.
> Can you give some help ? Thanks!

hi, on dev dataset and eval dataset,l set class=2,and get eer 0.96,2.29 respectively,l could see your code.and no find num_classes=10 pretrained model, thanks
